trigger:
  branches:
    include:
    - feature/*
    - release/*
    - develop
  paths:
    include:
    - azuredatafactory
    
pool:
  vmImage: 'ubuntu-latest'

variables:
  workingDir: $(Build.Repository.LocalPath)/azuredatafactory/src
  serviceConnection: 'AzureServiceConnection' 

stages:
  - stage: build
    jobs:
      - job:
      
        steps:
          
          # configuring node
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
          
          - task: Npm@1
            inputs:
              command: 'install'
              verbose: true
              workingDir: '$(workingDir)'
            displayName: 'Install npm package'
          
          # validating artifacts
          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run build validate $(workingDir) /subscriptions/337ba254-3aa0-4551-ba8e-89debefaa373/resourceGroups/RG-Datafactory/providers/Microsoft.DataFactory/factories/adf-testdeploywes'
              workingDir: '$(workingDir)'
            displayName: 'Validate'
